server:
  port: 8080

spring:
  application:
    name: oktaguard

okta:
  domain: ${OKTA_DOMAIN:https://trial-4746172.okta.com}
  api-token: ${OKTA_API_TOKEN:<YOUR_API_TOKEN>}
  client-id: ${OKTA_CLIENT_ID:<YOUR_CLIENT_ID>}
  client-secret: ${OKTA_CLIENT_SECRET:<YOUR_CLIENT_SECRET>}
